<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<!DOCTYPE html>
<html>
  <head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body style="font-family:Helvetica, Arial, sans-serif; color:#333; font-size:13px;">
    <table width="600" border="0">
      <tr style="background-color:#403f3f; height:35px;">
        <td style="padding: 10px 10px 0; color:#fff; display:inline-block; font-size:17px;">
         

        </td>
      </tr>
      <tr style="text-align:right; font-weight:bold;">
        <td style="padding: 10px;" >
            <a href="<?php echo $this->serverUrl($this->url('login')) ;?>" style="text-decoration :none; color:#333; margin-right:10px; font-weight:bold;">Sign In</a>
<!--    		  <a href="http://app.cloudforge.com/help" style="text-decoration:none; color:#333; margin-right:10px; font-weight:bold;">Help</a>-->
    		  <a href="<?php echo $this->serverUrl($this->url('home')) ;?>" style="text-decoration:none; color:#333; margin-right:10px; font-weight:bold;">www.movingswitch.com
</a>
        </td>
      </tr>
      <tr>
        <td style="padding: 10px;">
          <h1 style="font-size:24px; color:#aaa; margin:15px 0px 0px 0px;">Please reset your password</h1>
        </td>
      </tr>
      <tr>
        <td style="padding:0px 10px 20px 10px;">
          <p style="margin-bottom:5px; font-weight:bold;">Hi <?php echo $this->params['firstname']." ".$this->params['lastname'];?>,</p>
          <p style="width:400px; margin-top:5px;">Please click the below link to reset password.</p><br />
          <p style="width:400px; margin-top:5px;"><em style="text-decoration:underline; margin-bottom:5px; display:inline-block;">Here are the details:</em>
          
            <br />
            Username: <strong><?php echo $this->params['username'];?></strong>
          </p><br />
          <a href="<?php echo $this->serverUrl($this->params['url']);?>" style="text-decoration:none; color:#333; margin-left:10px; font-weight:bold; background-color:#6cadde; color:#325976; font-weight:bold !important; text-align:center !important; cursor:pointer !important; border:none !important;padding:8px; font-size:14px; line-height:50px; padding:5px; color:#325976 !important; text-decoration:none; height:80px; vertical-align:top;  border-radius:8px; ">Click here to reset your password.</a>
          <span style="font-size:11px; margin-top:10px; display:inline-block;">
            If you have any trouble with your new login, please contact your project administrator or email:<strong>support@movingswitch.com</strong>
          </span>
          <p>Thank you,<br>The MovingSwitch Team</p>
          <span style="font-size:11px;">
            Please do not reply directly to this email.
          </span>
        </td>
      </tr>

    </table>
  </body>
</html>
