<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
        
        <?php echo $this->headTitle($this->translate('Moving Switch'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

	<!-- BEGIN GLOBAL MANDATORY STYLES -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => IMG_PATH . '/favicon.ico'))
                ->prependStylesheet(PLUGINS_PATH . '/bootstrap/css/bootstrap.min.css')
                ->prependStylesheet(PLUGINS_PATH . '/bootstrap/css/bootstrap-responsive.min.css')
                ->prependStylesheet(PLUGINS_PATH . '/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet(CSS_PATH . '/style-metro.css')
                ->prependStylesheet(CSS_PATH . '/style.css')
                ->prependStylesheet(CSS_PATH . '/style-responsive.css')
                ->prependStylesheet(CSS_THEMES_PATH . '/default.css')
                ->prependStylesheet(PLUGINS_UNIFORM_PATH . '/css/uniform.default.css')
                ->prependStylesheet(CSS_PATH . '/pages/login-soft.css')
        ?>
	<!-- END GLOBAL MANDATORY STYLES -->
        
	<!-- END PAGE LEVEL STYLES -->
	<link rel="shortcut icon" href="favicon.ico" />
        
<style>
        .input-icon.left input {
                padding-left: 33px !important;
        }
        .btn {
                background-image: none !important;
        }
</style>

</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
	<!-- BEGIN LOGO -->
	<div class="logo">
		<!--img src="<?php echo IMG_PATH; ?>/logo-big.png" alt="" /--> 
	</div>
	<!-- END LOGO -->
	<!-- BEGIN LOGIN -->
	<div class="content">
		<!-- BEGIN LOGIN FORM -->
		<?php
			$form = $this->form;
			$form->prepare();
			$form->setAttribute('action', $this->url('forgot-password'));
			$form->setAttribute('method', 'post');
			$form->setAttribute('class', 'form-vertical login-form');
		?>
		<?php echo $this->form()->openTag($form) ?>
			<h3 class="form-title">Forgot Password</h3>
			<?php $errors = $this->formElementErrors($form); ?>
			<div class="alert alert-error <?php echo ($errors) ? '' : 'hide';?>">
				<span class="close" data-dismiss="alert"></span>
				<?php echo $errors; ?>
			</div>
			<div class="control-group">
				<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
				<label class="control-label visible-ie8 visible-ie9"><?php echo $this->formLabel($form->get('email')) ?></label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-envelope"></i>
						<?php echo $this->formInput($form->get('email')) ?>
					</div>
				</div>
			</div>
			
			<div class="form-actions">
                            <div class="pull-right">
				<?php //echo $this->formSubmit($form->get('submit')); ?>
                                
                                <button type="submit" class="btn blue pull-left">
                                    Send <i class="m-icon-swapright m-icon-white"></i>
				</button>
                                &nbsp;
                                <a  href="<?php echo $this->url('login'); ?>" id="return_login" class="btn"/>Return to Login <a/>
                                
                            </div>
			</div>
			
		<?php echo $this->form()->closeTag() ?>
		<!-- END LOGIN FORM -->
	</div>
	<!-- END LOGIN -->
	<!-- BEGIN COPYRIGHT -->
	<div class="copyright">
		2013 &copy; by NeoSoft.
	</div>
	<!-- END COPYRIGHT -->
	<!-- END COPYRIGHT -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->
	<script src="<?php echo PLUGINS_PATH;?>/jquery-1.10.1.min.js" type="text/javascript"></script>
	<script src="<?php echo PLUGINS_PATH;?>/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
	<script src="<?php echo PLUGINS_PATH;?>/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      
	<script src="<?php echo PLUGINS_PATH;?>/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!--[if lt IE 9]>
	<script src="<?php echo PLUGINS_PATH;?>/excanvas.min.js"></script>
	<script src="<?php echo PLUGINS_PATH;?>/respond.min.js"></script>  
	<![endif]-->   
	<script src="<?php echo PLUGINS_PATH;?>/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="<?php echo PLUGINS_PATH;?>/jquery.blockui.min.js" type="text/javascript"></script>  
	<script src="<?php echo PLUGINS_PATH;?>/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="<?php echo PLUGINS_UNIFORM_PATH;?>/jquery.uniform.min.js" type="text/javascript" ></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<!--<script src="<?php echo PLUGINS_PATH;?>/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>-->
        <script src="<?php echo PLUGINS_PATH;?>/backstretch/jquery.backstretch.min.js" type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="<?php echo SCRIPTS_PATH;?>/app.js" type="text/javascript"></script>
	<script src="<?php echo SCRIPTS_PATH;?>/login-soft.js" type="text/javascript"></script>
	<!-- END PAGE LEVEL SCRIPTS -->
        <script>
		jQuery(document).ready(function() {     
                    App.init();
                    Login.init();
                  
                    $("#email").focus();

                    $("#cancel").click(function() {
                        $("#username").val('');
                        $("#password").val('');
                        $("#username").focus();
                    })
                  
		});
	</script>
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>