	<div class="container">
<?php
		if (count($messages) > 0) {
			foreach($messages as $id  => $message)
			{
				print $message."<br />";
			}
		}
		$form = $this->form;
		$form->prepare();
		$form->setAttribute('action', $this->url('login'));
		$form->setAttribute('method', 'post');
		$form->setAttribute('class', 'form-signin');
		echo $this->form()->openTag($form); 
		$errors = $this->formElementErrors($form); 
?>
				<h2 class="form-signin-heading">Please sign in</h2>
				<div class="alert alert-error <?php echo ($errors) ? '' : 'hide';?>">
					<span class="close" data-dismiss="alert"></span>
					<?php echo $errors; ?>
				</div>
				<div class="control-group">
					<div class="controls">
						<div class="input-icon left">
							<?php echo $this->formInput($form->get('email')) ?>
						</div>
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<div class="input-icon left">
							<?php echo $this->formInput($form->get('password')) ?>
						</div>
					</div>
				</div>
				<?php echo $this->formSubmit($form->get('submit')) ?>
			<?php echo $this->form()->closeTag() ?>
	</div> <!-- /container -->