<?php echo $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
        
	<?php echo $this->headTitle($this->translate('Moving Switch'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => IMG_PATH . '/favicon.ico'))
                        ->prependStylesheet(PLUGINS_PATH . '/bootstrap/css/bootstrap.min.css')
                        ->prependStylesheet(PLUGINS_PATH . '/bootstrap/css/bootstrap-responsive.min.css')
                        ->prependStylesheet(PLUGINS_PATH . '/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet(CSS_PATH . '/style-metro.css')
                        ->prependStylesheet(CSS_PATH . '/style.css')
                        ->prependStylesheet(CSS_PATH . '/style-responsive.css')
                        ->prependStylesheet(CSS_PATH . '/themes/default.css')
                        ->prependStylesheet(PLUGINS_UNIFORM_PATH . '/css/uniform.default.css')
                        ->prependStylesheet(CSS_PATH . '/pages/login.css') ?>

	<style>
		.input-icon.left input {
			padding-left: 33px !important;
		}
		.btn {
			background-image: none !important;
		}
	</style>

</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
	<!-- BEGIN LOGO -->
	<div class="logo">
		
	</div>
	<!-- END LOGO -->
	<!-- BEGIN LOGIN -->
	<div class="content">
		<!-- BEGIN LOGIN FORM -->
		<?php
			$form->setAttribute('action', $this->url('reset-password',array('code' => $this->token)));
			$form->setAttribute('method', 'post');
			$form->setAttribute('class', 'form-vertical login-form');
		?>
		<?php echo $this->form()->openTag($form) ?>
                <?php echo $this->formInput($form->get('access_token')) ?>
			<h3 class="form-title">Password reset</h3>
			<?php $errors = $this->formElementErrors($form); ?>
			<div class="alert alert-error <?php echo ($errors) ? '' : 'hide';?>">
				<button class="close" data-dismiss="alert"></button>
				<?php echo $errors; ?>
			</div>
			<div class="control-group">
				<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
				<label class="control-label visible-ie8 visible-ie9"><?php echo $this->formLabel($form->get('password')) ?></label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-lock"></i>
						<?php echo $this->formInput($form->get('password')) ?>
					</div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label visible-ie8 visible-ie9"><?php echo $this->formLabel($form->get('retype_password')) ?></label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-lock"></i>
						<?php echo $this->formInput($form->get('retype_password')) ?>
					</div>
				</div>
			</div>
			<div class="form-actions">

<!--				<label class="checkbox">
					<input type="checkbox" name="remember" value="1"/> Remember me
				</label>-->

				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
			
		<?php echo $this->form()->closeTag() ?>
		
	</div>
	<!-- END LOGIN -->
	<!-- BEGIN COPYRIGHT -->
	<div class="copyright">
		2013 &copy; by NeoSoft.
	</div>
	<!-- END COPYRIGHT -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->
	<script src="<?php echo PLUGINS_PATH;?>/jquery-1.10.1.min.js" type="text/javascript"></script>
	<script src="<?php echo PLUGINS_PATH;?>/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
	<script src="<?php echo PLUGINS_PATH;?>/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>      
	<script src="<?php echo PLUGINS_PATH;?>/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!--[if lt IE 9]>
	<script src="<?php echo PLUGINS_PATH;?>/excanvas.min.js"></script>
	<script src="<?php echo PLUGINS_PATH;?>/respond.min.js"></script>  
	<![endif]-->   
	<script src="<?php echo PLUGINS_PATH;?>/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="<?php echo PLUGINS_PATH;?>/jquery.blockui.min.js" type="text/javascript"></script>  
	<script src="<?php echo PLUGINS_PATH;?>/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="<?php echo PLUGINS_UNIFORM_PATH;?>/jquery.uniform.min.js" type="text/javascript" ></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<!--script src="<?php echo PLUGINS_PATH;?>/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script-->
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="<?php echo SCRIPTS_PATH;?>/app.js" type="text/javascript"></script>
	<script src="<?php echo SCRIPTS_PATH;?>/login.js" type="text/javascript"></script>      
	<!-- END PAGE LEVEL SCRIPTS --> 
	<script>
		jQuery(document).ready(function() {     
		  App.init();
		});
	</script>
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
