<style>
    label{
        float: left;
        margin-left: 0 !important;
        width: 30% !important;
    }
    select {
        width: 250px;
    }
</style>

<?php
	$title = 'Permissions - Set Dependencies';
	$this->headTitle($title);
?>

<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption"><i class="icon-user"></i><?php echo $this->escapeHtml($title); ?></div>
        <div class="tools">
        </div>
    </div>
    
    <div class="portlet-body">
        <div class="clearfix">
            <div class="btn-group">
                
            </div>
        </div>
        <div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
            <div class="row-fluid">
                <div class="span6">
                    <div id="sample_1_length" class="dataTables_length">
                    </div>
                </div>
            </div>
	    
            <table class="table table-striped table-bordered table-hover dataTable" id="sample_1" aria-describedby="sample_1_info">
                <thead>
                    <tr>
                        <td>
                            <h5>Select Main Permission:</h5>
                        </td>
                        
                        <td>
                            <h5>Select Dependent Permissions:</h5>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Module List:&nbsp;&nbsp;</label>
                            <select name="main_modules" id="main_modules">
                                <option value="">-- Select Module --</option>
                                <?php
                                    foreach($modules as $module) {
                                ?>
                                        <option value='<?php echo $module->id; ?>'><?php echo $module->name; ?></option>
                                <?php        
                                    }
                                ?>
                            </select>
                        </td>
                        
                        <td rowspan="3">
                            <label>Dependent Permission:&nbsp;&nbsp;</label>
                            <select size="20" name="dependent_permissions" id="dependent_permissions" multiple>
                                <option value="">-- Select Dependent Permission --</option>
                            </select>
                        </td>
                    </tr>
                    
                    <tr>
                        <td>
                            <label>Controller List:&nbsp;&nbsp;</label>
                            <select name="main_controllers" id="main_controllers">
                                <option value="">-- Select Controller --</option>
                            </select>
                        </td>
                    </tr>
                    
                    <tr>
                        <td>
                            <label>Permission List:&nbsp;&nbsp;</label>
                            <select size="15" name="main_permissions" id="main_permissions">
                                <option value="">-- Select Permission --</option>
                            </select>
                        </td>
                    </tr>
                    
                </thead>
            </table>
            
            <table class="table table-striped table-bordered table-hover dataTable" id="sample_3" aria-describedby="sample_3_info">

                <thead>
                    <tr>
                        <th colspan="3">
                            Already Set Dependency for selected Main permission:
                        </th>
                    </tr>
                    
                    <tr>
                        <th>Module:</th>
                        <th>Controller:</th>
                        <th>Permission:</th>
                    </tr>
                    
                </thead>
                <tbody role="alert" aria-live="polite" aria-relevant="all">
                    
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    
                </tbody>
            </table>
            
            <table class="table table-striped table-bordered table-hover dataTable" id="sample_1" aria-describedby="sample_1_info">

                <tbody role="alert" aria-live="polite" aria-relevant="all">
                    
                    <tr>
                        <td>
                            <div class="row-fluid">
                                <div class="span12 ">
                                    <div class="form-permissions">
                                        <a style="display:none;" id="submit" href="javascript:void(0)" class="btn blue" >Set Dependency</a>
                                        <a href="<?php echo $this->url('auth',array('action'=>'set-permission-dependency')); ?>" class="btn" >Cancel</a>
                                        <input type="hidden" name="unselected_permissions" id="unselected_permissions" value="" />
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    
                </tbody>
            </table>
            
            <div class="row-fluid">
            </div>
            
        </div>
        
    </div>
    
</div>

<script>
    
    /**
     * Populates the Controllers drop-down box
     * @returns {undefined}
     */
    function loadControllers() {
        
        var module_id = $('#main_modules').val();
        
        $('select[id="main_controllers"]').empty();
        $('select[id="main_permissions"]').empty();
        disableDependents();
        
        if(module_id === '') {
            disableDependents();
            return false;
        }
        
        var item_id = $('select[id="main_controllers"]');
            
            //First Empty the Select Box
            $(item_id).empty();

        var data = {
            'module_id':module_id,
        };
    
        $.ajax({
            async: false,
            type: 'POST',
            data: {data : data},
            dataType: 'JSON',
            url: '<?php echo $this->url('auth', array('action' => 'set-permission-dependency')); ?>',
            beforeSend: function() {
            },
            success:function(data){
                if(data.status === null) {
                    alert("Permission Denied!");
                }
                else if(data.status) {
                    $(item_id).append($("<option />").val('').text("-- Select Controller --"));
                    $.each(data.div, function(key, val){
                        $(item_id).append($("<option />").val(key).text(val));
                    });
                }
                else
                    alert("Error occured while loading Module's Controllers! Please try again.");
            },
            error: function() {
                 alert("Error occured! Please try again.");
            },
        });

    }
    
    /**
     * Populates the permissions drop-down box
     * @returns {undefined}
     */
    function loadPermissions() {
        
        var controller_id = $('#main_controllers').val();
        
        $('select[id="main_permissions"]').empty();
        disableDependents();
        
        if(controller_id === '') {
            disableDependents();
            return false;
        }
        
        var item_id = $('select[id="main_permissions"]');
            
            //First Empty the Select Box
            $(item_id).empty();

        var data = {
            'controller_id':controller_id,
        };
    
        $.ajax({
            async: false,
            type: 'POST',
            data: {data : data},
            dataType: 'JSON',
            url: '<?php echo $this->url('auth', array('action' => 'set-permission-dependency')); ?>',
            beforeSend: function() {
            },
            success:function(data){
                if(data.status === null) {
                    alert("Permission Denied!");
                }
                else if(data.status) {
                    $(item_id).append($("<option />").val('').text("-- Select Permission --"));
                    $.each(data.div, function(key, val){
                        $(item_id).append($("<option />").val(key).text(val));
                    });
                }
                else
                    alert("Error occured while loading Controller's permissions! Please try again.");
            },
            error: function() {
                 alert("Error occured! Please try again.");
            },
        });

    }
    
    /**
     * Populates the permissions drop-down box
     * @returns {undefined}
     */
    function loadDependentPermissions() {
        
        var main_controller_id = $('#main_controllers').val();
        var main_action_id = $('#main_permissions').val();
        
        if(main_controller_id !== '' && main_action_id === '') {
            disableDependents();
            return false;
        }
        
        if(main_controller_id === '') {
            return false;
        }
        
        var item_id = $('select[id="dependent_permissions"]');
            
            //First Empty the Select Box
            $(item_id).empty();

        var data = {
            'main_controller_id':main_controller_id,
            'main_action_id':main_action_id,
        };
    
        $.ajax({
            async: false,
            type: 'POST',
            data: {data : data},
            dataType: 'JSON',
            url: '<?php echo $this->url('auth', array('action' => 'set-permission-dependency')); ?>',
            beforeSend: function() {
            },
            success:function(data){
                if(data.status === null) {
                    alert("Permission Denied!");
                }
                else if(data.status) {
                    $(item_id).append($("<option />").val('').text("-- Select Dependent Permission --"));
                    $.each(data.div.actions, function(key, val){
                        $(item_id).append($("<option />").val(key).text(val));
                    });
                    
                    //Auto-select the options from dependent_permissions
                    $.each(data.div.old_dependent_permission_ids, function(key, val){
                        $('select[id="dependent_permissions"] option[value="' + val + '"]').attr("selected", 1);
                    });
                    
                    //Auto - load the Already Set Dependent Permissions
                    loadAlreadySetDependentPermissions();
                    
                    $('#submit').css('display', 'inline');
                    $('select[id="dependent_permissions"]').attr('disabled', false);
                }
                else
                    alert("Error occured while loading Dependent's permissions! Please try again.");
            },
            error: function() {
                 alert("Error occured! Please try again.");
            },
        });

    }
    
    $('#dependent_permissions').change(function(){
        var unselected_permissions = '';
        
        $('#dependent_permissions option').each(function(){
            if(!$(this).is(':selected'))
                unselected_permissions += $(this).val() + ',';
        });
        
        $('#unselected_permissions').val(unselected_permissions);
        
    });
    
    function loadAlreadySetDependentPermissions() {
        var main_permission_id = $('#main_permissions').val();
        var body_element = $('#sample_3 tbody');
        
        if(main_permission_id == '') {
            resetExtraInfo();
            return false;
        }
        else if(main_permission_id != '') {
            
            var data = {
                'main_permission_id':main_permission_id
            };

            $.ajax({
                async: false,
                type: 'POST',
                data: {data : data},
                dataType: 'JSON',
                url: '<?php echo $this->url('auth', array('action' => 'set-permission-dependency')); ?>',
                beforeSend: function() {
                },
                success:function(data){
                    if(data.status === null) {
                        alert("Permission Denied!");
                    }
                    else if(data.status) {
                        if(data.status == true) {
                            
                            if(data.div) {
                                $(body_element).empty();
                                
                                if(data.div.length > 0) {
                                    $(data.div).each(function(key, val){
                                        var row = val;
                                        $(row).each(function(key, val){
                                            if(body_element) {
                                                $(body_element).append(
                                                    '<tr>' +
                                                        '<td>' + val.module_name + '</td>' +
                                                        '<td>' + val.controller_name + '</td>' +
                                                        '<td>' + val.title + '</td>' +
                                                    '</tr>'
                                                );
                                            }
                                        }); 
                                    });
                                }
                                else {
                                    $(body_element).append(
                                        '<tr>' +
                                            '<td colspan="3">No Dependency found.</td>' +
                                        '</tr>'
                                    );
                                }
                            }
                        }
                    }
                },
                error: function() {
                     alert("Error occured! Please try again.");
                },
            });
        }
    }
    
    function resetExtraInfo() {
        $('#sample_3 tbody').empty();
        $('#sample_3 tbody').html(
            '<tr>' +
                '<td colspan="3">Please select a Main Permission to view its dependencies.</td>' +
            '</tr>'
        );
    }
    
    function disableDependents() {
    
        $('select[id="dependent_permissions"]').html($("<option />").val('').text("-- Select Dependent Permission --"));
    
        $('select[id="dependent_permissions"]').attr('disabled', 'disabled');
        
        $('#submit').css('display', 'none');
    }
    
    $(document).ready(function(){
        
        disableDependents();
        resetExtraInfo();
        
        $(document).on('change', '#main_modules', function() {
            loadControllers();
            resetExtraInfo();
        });
        
        $(document).on('change', '#main_controllers', function() {
            loadPermissions();
            resetExtraInfo();
        });
        
        $(document).on('change', '#main_permissions', function() {
            var main_controller_id = $('#main_controllers').val();
            if($('#main_permissions').val() == '') {
                disableDependents();
                resetExtraInfo();
                return false;
            }
            
            //loadAlreadySetDependentPermissions();
            
            loadDependentPermissions();
        });
        
        $('#submit').click(function(){
            var main_permission_id = $('#main_permissions').val();
            var dependent_permissions_id = $('#dependent_permissions').val();
            var unselected_permissions_id = $('#unselected_permissions').val();
            
            if(dependent_permissions_id == null && unselected_permissions_id == '') {
                alert("Please select atleast 1 Dependent Permission");
                return false;
            }
            else if(dependent_permissions_id == '' && dependent_permissions_id.length == 1) {
                alert("Please select atleast 1 Dependent Permission");
                return false;
            }
            else if(dependent_permissions_id != null && dependent_permissions_id.length == 1 && dependent_permissions_id[0] == "" && unselected_permissions_id == '') {
                alert("Please select atleast 1 Dependent Permission");
                return false;
            }
            else if(dependent_permissions_id != null && dependent_permissions_id.length == 1 && dependent_permissions_id[0] == "") {
                dependent_permissions_id = null;
            }
            
            var data = {
                'main_permission_id':main_permission_id,
                'dependent_permissions_ids':dependent_permissions_id,
                'unselected_permissions_id':unselected_permissions_id
            };

            $.ajax({
                async: false,
                type: 'POST',
                data: {data : data},
                dataType: 'JSON',
                url: '<?php echo $this->url('auth', array('action' => 'set-permission-dependency')); ?>',
                beforeSend: function() {
                },
                success:function(data){
                    if(data.status === null) {
                        alert("Permission Denied!");
                    }
                    else if(data.status) {
                        if(data.status == true) {
                            
                            //Load Already Set Dependent Permissions
                            loadAlreadySetDependentPermissions();
                            
                            alert(data.div);
                        }
                        else
                            alert('Error occured while Setting Permission Dependency.');
                    }
                    else
                        alert("Error occured while setting Permission Dependency! Please try again.");
                },
                error: function() {
                     alert("Error occured! Please try again.");
                },
            });
    
        });
    });
</script>