	<div class="container">
		<div class="form-signin">
			<h2 class="form-signin-heading"><?php print $title; ?></h2>
<?php  
			if (count($messages) > 0) {
				print '<div class="success">';
				foreach($messages as $id  => $message)
				{
					print $message."<br />";
				}
				print '</div>';
			}
			$escaper = new Zend\Escaper\Escaper('utf-8');
			if (isset($userDetails->firstname)) print '<br />First Name: '.$escaper->escapeHtml($userDetails->firstname);
			if (isset($userDetails->lastname)) print '<br />Last Name: '.$escaper->escapeHtml($userDetails->lastname);
			if (isset($userDetails->email)) print '<br />Email: '.$escaper->escapeHtml($userDetails->email);
?>
			<div id="image" style="padding:10px;"></div>
			<button class="btn btn-small btn-primary" type="submit" id="showimage">Show Avatar</button>
			<script>
				$( "#showimage" ).on( "click", function( event ) {
					$.ajax({
						  url: "/image",
						  data: {
						    userid: <?php  print $escaper->escapeHtml($userDetails->id); ?>
						  },
						  success: function( data ) {
						    $( "#image" ).html( data.image );
						  }
						});
				});
			</script>
		</div>
	</div>